### ISSUE TITLE
factor out CED

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/mease-lab-to-nwb#2]
It's fine to keep CED stuff in here for now, but eventually we'll want to factor this out into spikeextractors and/or nwb-conversion-tools so it can be used for other labs.

**Comment by CodyCBakerPhD** [comment]
@bendichter Is this still an issue for this repo?

**Comment by bendichter** [comment]
I suppose not. It looks like the DataInterface might be pretty specific to this project.
