### ISSUE TITLE
Dimension Errors in recording_processed 

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#34]
![image](https://user-images.githubusercontent.com/43117750/117019377-a29b8c00-acf5-11eb-9511-87043a4de4d1.png)

Sampling frequency = 30kHz

![image](https://user-images.githubusercontent.com/43117750/117019525-c2cb4b00-acf5-11eb-9279-9b4593bf9838.png)
![image](https://user-images.githubusercontent.com/43117750/117019553-cb238600-acf5-11eb-894b-5682142aecb1.png)

sw.plot_timeseries(recording_processed) gives - ValueError: x and y must have same first dimension, but have shapes (10000,) and (9702,)

(stubtest = false)

Maybe this was due to difference in sampling frequency in CED SI pipeline (30kHz) vs Intan sampling frequency (30.003kHz)?

**Comment by rf13734** [comment]
This issue kinda persists for the spikesorting section as well

![Uploading image.png…]()

**Comment by alejoe91** [comment]
@luiztauffer this seems to be due to a mismatch in the returned traces by the CED extractor. Can you look into this? @rf13734 can you upload the full file on drive?

**Comment by rf13734** [comment]
> @luiztauffer this seems to be due to a mismatch in the returned traces by the CED extractor. Can you look into this? @rf13734 can you upload the full file on drive?

Yes it will be the file called pt1 15+mech 
![image](https://user-images.githubusercontent.com/43117750/117022385-80573d80-acf8-11eb-988a-6fbaba15adeb.png)

**Comment by luiztauffer** [comment]
@rf13734 thanks for reporting this! I'll look into that this coming week

**Comment by rf13734** [comment]
> @rf13734 thanks for reporting this! I'll look into that this coming week

Thanks, much appreciated!
Ross

**Comment by rf13734** [comment]
@luiztauffer 
![image](https://user-images.githubusercontent.com/43117750/117783920-4a0f4600-b243-11eb-84ae-5500b46f144e.png)
Also got the same issue with a different smrx file from the same experiment
![image](https://user-images.githubusercontent.com/43117750/117784030-6612e780-b243-11eb-86aa-264405bf101d.png)

**Comment by luiztauffer** [comment]
@rf13734 is it possible for you to make test recordings with this system? So we could try different configurations (e.g. output file format). The data of course doesn't need to be real electrophys
I'll try to get in touch with sonpy developers

**Comment by rf13734** [comment]
@luiztauffer Yeah sure! You reckon 32 bit smr Big file would be a good start?
![image](https://user-images.githubusercontent.com/43117750/117804039-95cbea80-b257-11eb-9074-59952a0a96ac.png)

**Comment by luiztauffer** [comment]
the changes to get_traces will soon be in place. Meanwhile, it is worth to discover why there are such time offsets. There could be different time offset values for different signals. For example, for your file:
```python
fname = 'pt1 15 + mech.smrx'
channel_info = ced.get_all_channels_info(fname)
for ch, info in channel_info.items():
    print(info['title'], ' - ', info['time_offset'])
```
```
RhdD-0  -  298.0
RhdD-1  -  298.0
RhdD-2  -  298.0
RhdD-3  -  298.0
RhdD-4  -  298.0
RhdD-5  -  298.0
RhdD-6  -  298.0
RhdD-7  -  298.0
RhdD-8  -  298.0
RhdD-9  -  298.0
RhdD-10  -  298.0
RhdD-11  -  298.0
RhdD-12  -  298.0
RhdD-13  -  298.0
RhdD-14  -  298.0
RhdD-15  -  298.0
RhdD-16  -  298.0
RhdD-17  -  298.0
RhdD-18  -  298.0
RhdD-19  -  298.0
RhdD-20  -  298.0
RhdD-21  -  298.0
RhdD-22  -  298.0
RhdD-23  -  298.0
RhdD-24  -  298.0
RhdD-25  -  298.0
RhdD-26  -  298.0
RhdD-27  -  298.0
RhdD-28  -  298.0
Keyboard  -  -11.0
RhdD-29  -  298.0
RhdD-30  -  298.0
RhdD-31  -  298.0
RhdD-32  -  298.0
RhdD-33  -  298.0
RhdD-34  -  298.0
RhdD-35  -  298.0
RhdD-36  -  298.0
RhdD-37  -  298.0
RhdD-38  -  298.0
RhdD-39  -  298.0
RhdD-40  -  298.0
RhdD-41  -  298.0
RhdD-42  -  298.0
RhdD-43  -  298.0
RhdD-44  -  298.0
RhdD-45  -  298.0
RhdD-46  -  298.0
RhdD-47  -  298.0
RhdD-48  -  298.0
RhdD-49  -  298.0
RhdD-50  -  298.0
RhdD-51  -  298.0
RhdD-52  -  298.0
RhdD-53  -  298.0
RhdD-54  -  298.0
RhdD-55  -  298.0
RhdD-56  -  298.0
RhdD-57  -  298.0
RhdD-58  -  298.0
RhdD-59  -  298.0
RhdD-60  -  298.0
RhdD-61  -  298.0
RhdD-62  -  298.0
RhdD-63  -  298.0
CED_Mech  -  0.0
LFP  -  298.0
Resp Rate  -  298.0
MechTTL  -  298.0
MechStim  -  298.0
Laser  -  298.0
Brush  -  298.0
Poke  -  298.0
```

**Comment by rf13734** [comment]
@luiztauffer Thanks very much, the last pull request for spikexctractors fixed it! All the best!

Ross

**Comment by rf13734** [comment]
Apologies @luiztauffer , think I spoke too soon. It didn't fail where it failed last time, but still fails at 98% when writing to the dat file
![image](https://user-images.githubusercontent.com/43117750/118158260-d4aa9d80-b41b-11eb-9f85-0a8fdf83e658.png)

![image](https://user-images.githubusercontent.com/43117750/118158318-e7bd6d80-b41b-11eb-80d0-3a83eb2faf7b.png)

**Comment by rf13734** [comment]
> the changes to get_traces will soon be in place. Meanwhile, it is worth to discover why there are such time offsets. There could be different time offset values for different signals. For example, for your file:
> 
> ```python
> fname = 'pt1 15 + mech.smrx'
> channel_info = ced.get_all_channels_info(fname)
> for ch, info in channel_info.items():
>     print(info['title'], ' - ', info['time_offset'])
> ```
> 
> ```
> RhdD-0  -  298.0
> RhdD-1  -  298.0
> RhdD-2  -  298.0
> RhdD-3  -  298.0
> RhdD-4  -  298.0
> RhdD-5  -  298.0
> RhdD-6  -  298.0
> RhdD-7  -  298.0
> RhdD-8  -  298.0
> RhdD-9  -  298.0
> RhdD-10  -  298.0
> RhdD-11  -  298.0
> RhdD-12  -  298.0
> RhdD-13  -  298.0
> RhdD-14  -  298.0
> RhdD-15  -  298.0
> RhdD-16  -  298.0
> RhdD-17  -  298.0
> RhdD-18  -  298.0
> RhdD-19  -  298.0
> RhdD-20  -  298.0
> RhdD-21  -  298.0
> RhdD-22  -  298.0
> RhdD-23  -  298.0
> RhdD-24  -  298.0
> RhdD-25  -  298.0
> RhdD-26  -  298.0
> RhdD-27  -  298.0
> RhdD-28  -  298.0
> Keyboard  -  -11.0
> RhdD-29  -  298.0
> RhdD-30  -  298.0
> RhdD-31  -  298.0
> RhdD-32  -  298.0
> RhdD-33  -  298.0
> RhdD-34  -  298.0
> RhdD-35  -  298.0
> RhdD-36  -  298.0
> RhdD-37  -  298.0
> RhdD-38  -  298.0
> RhdD-39  -  298.0
> RhdD-40  -  298.0
> RhdD-41  -  298.0
> RhdD-42  -  298.0
> RhdD-43  -  298.0
> RhdD-44  -  298.0
> RhdD-45  -  298.0
> RhdD-46  -  298.0
> RhdD-47  -  298.0
> RhdD-48  -  298.0
> RhdD-49  -  298.0
> RhdD-50  -  298.0
> RhdD-51  -  298.0
> RhdD-52  -  298.0
> RhdD-53  -  298.0
> RhdD-54  -  298.0
> RhdD-55  -  298.0
> RhdD-56  -  298.0
> RhdD-57  -  298.0
> RhdD-58  -  298.0
> RhdD-59  -  298.0
> RhdD-60  -  298.0
> RhdD-61  -  298.0
> RhdD-62  -  298.0
> RhdD-63  -  298.0
> CED_Mech  -  0.0
> LFP  -  298.0
> Resp Rate  -  298.0
> MechTTL  -  298.0
> MechStim  -  298.0
> Laser  -  298.0
> Brush  -  298.0
> Poke  -  298.0
> ```




The offset is probably due all the signals being passed through intan, except for the CED_Mech and the keyboard marker. However it's not obvious to me where to alter this.
![image](https://user-images.githubusercontent.com/43117750/118161344-be064580-b41f-11eb-879c-912262a5dde5.png)

**Comment by alejoe91** [comment]
@luiztauffer maybe there is also a time_offset at the end???

**Comment by luiztauffer** [comment]
well, it looks like `chunks` is being created with the wrong size here:
https://github.com/SpikeInterface/spikeextractors/blob/c6528d34754bbc4ef78a0c57766f8873ae55e71b/spikeextractors/extraction_tools.py#L360

this makes sense, we should include the time-offset here:
https://github.com/SpikeInterface/spikeextractors/blob/c6528d34754bbc4ef78a0c57766f8873ae55e71b/spikeextractors/extractors/cedextractors/cedrecordingextractor.py#L140

**Comment by alejoe91** [comment]
Yes, then I would say that the CED num frames is wrong, not the chunk size :P

**Comment by luiztauffer** [comment]
@rf13734 hopefully [this PR](https://github.com/SpikeInterface/spikeextractors/pull/639) will fix that now
together with the data, could you share the probe files associated with the recording? So I can run the spike sorting and test for any other possible errors?

**Comment by rf13734** [comment]
> @rf13734 hopefully [this PR](https://github.com/SpikeInterface/spikeextractors/pull/639) will fix that now
> together with the data, could you share the probe files associated with the recording? So I can run the spike sorting and test for any other possible errors?

@luiztauffer Thanks very much for your quick work! I've sent you the probe file.

**Comment by rf13734** [comment]
@luiztauffer  the files were sorted after the fix, many thanks!
