### ISSUE TITLE
Sampling Frequency mismatch

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#36]
@luiztauffer Hi Luiz,

All of the recordings I have put through the pipeline so far have been 30,030Hz (3.003003003003003*10^4). The CED pipeline keeps generating a sampling rate of 30,000Hz. I'm just curious as to the origins of the difference and whether or not this is a deliberate downsampling?

Many thanks.

Ross

![image](https://user-images.githubusercontent.com/43117750/118684094-385d0e00-b802-11eb-800a-470f25847112.png)
![image](https://user-images.githubusercontent.com/43117750/118684172-4874ed80-b802-11eb-99c9-aac5df7fc3ec.png)

![image](https://user-images.githubusercontent.com/43117750/118683217-7c034800-b801-11eb-871c-109d8801c5b1.png)
![image](https://user-images.githubusercontent.com/43117750/118683354-9b01da00-b801-11eb-9036-05dfdb1e2eed.png)

**Comment by luiztauffer** [comment]
@rf13734 thanks for finding that mismatch! 
It is indeed a confusing problem... we get this rate using the sonpy `GetIdealRate()` function and I have no idea why it diverges from the rate you set.
We can make it better though, using other sonpy functions:
`rate = 1 / (f.GetTimeBase() * f.ChannelDivide(1))`
this yields, for your file, `rate=30030.030030030033`, which is not exactly 30.030, but better than 30.000

**Comment by rf13734** [comment]
> @rf13734 thanks for finding that mismatch!
> It is indeed a confusing problem... we get this rate using the sonpy `GetIdealRate()` function and I have no idea why it diverges from the rate you set.
> We can make it better though, using other sonpy functions:
> `rate = 1 / (f.GetTimeBase() * f.ChannelDivide(1))`
> this yields, for your file, `rate=30030.030030030033`, which is not exactly 30.030, but better than 30.000

@luiztauffer This is actually the legit sampling rate as far as I know, so would be perfect, many thanks!!

**Comment by luiztauffer** [comment]
it should be fixed with [this PR](https://github.com/SpikeInterface/spikeextractors/pull/643)
