### ISSUE TITLE
No module named 'nwb_conversion_tools.utils.spike_interface'; 'nwb_conversion_tools.utils' is not a packag

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#39]
Hi @luiztauffer, I switched to the fixes branch to try the recent updates to the CED pipeline and get this error message. I have also updated the nwb-conversion-tools. I'm wondering what the issue might be?

Error Message:
![image](https://user-images.githubusercontent.com/43117750/119484251-1dd0ea80-bd56-11eb-9f40-cc19b056c1bb.png)

![image](https://user-images.githubusercontent.com/43117750/119484007-e3ffe400-bd55-11eb-8b9c-be56e0616c74.png)

![image](https://user-images.githubusercontent.com/43117750/119484093-f5e18700-bd55-11eb-81a3-930a86a2dac4.png)

![image](https://user-images.githubusercontent.com/43117750/119484223-16a9dc80-bd56-11eb-9e1a-483365ac52f8.png)

**Comment by luiztauffer** [comment]
@rf13734 could you please try to uninstall it first, then install the master branch again?
```
pip uninstall nwb-conversion-tools
```
this error should not happen in the current master branch.

**Comment by rf13734** [comment]
@luiztauffer It worked, thanks!

![image](https://user-images.githubusercontent.com/43117750/119491133-de0e0100-bd5d-11eb-92bc-5f361d765532.png)
