### ISSUE TITLE
'starting_time' type error for saving LFP objects

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#43]
Hi @luiztauffer  I'm trying to save the raw traces from each channel in my probe (I downsampled and low-pass filtered at 300Hz) but it seems like it might be using the local memory again to save, is this the case?
![image](https://user-images.githubusercontent.com/43117750/123091161-4d444700-d429-11eb-8df4-58f67a57ee3d.png)
![image](https://user-images.githubusercontent.com/43117750/123091176-51706480-d429-11eb-8004-ddb588cae509.png)

I also have this issue with the 'starting _time'
![image](https://user-images.githubusercontent.com/43117750/123091211-5e8d5380-d429-11eb-9f12-bfaac147284d.png)

**Comment by luiztauffer** [comment]
hi @rf13734 
just to check, are you using the recent code from the [open PR ](https://github.com/catalystneuro/mease-lab-to-nwb/pull/38)?
can you please also check if you're using the current master branch version of [nwb-conversion-tools](https://github.com/catalystneuro/nwb-conversion-tools)?

**Comment by rf13734** [comment]
Hi @luiztauffer. Sorry for not replying to this sooner, been quite a hectic few weeks! 

I think I'm up to date with the fixes #38 and the nwb-conversion tools,  I'm now getting this error when I try to import spikeextractors: ModuleNotFoundError: No module named 'neo'. Have I done something wrong maybe?

![image](https://user-images.githubusercontent.com/43117750/124731044-29493100-df12-11eb-9072-1cd774807171.png)

**Comment by rf13734** [comment]
![image](https://user-images.githubusercontent.com/43117750/124732127-374b8180-df13-11eb-9393-05bed753fc66.png)
![image](https://user-images.githubusercontent.com/43117750/124732276-5a763100-df13-11eb-91f5-47d1292ad4f0.png)
![image](https://user-images.githubusercontent.com/43117750/124732909-f6a03800-df13-11eb-8163-a019e7424bba.png)

Hope this is all correct!

**Comment by alejoe91** [comment]
@rf13734 can you `pip install neo`?

**Comment by alejoe91** [comment]
Actually you have to install neo from master too..

**Comment by rf13734** [comment]
@alejoe91  Like this?
![image](https://user-images.githubusercontent.com/43117750/124737929-ba230b00-df18-11eb-8659-d6b5068cceff.png)

I still get the error

![image](https://user-images.githubusercontent.com/43117750/124738064-dc1c8d80-df18-11eb-8d24-be53d018887b.png)

**Comment by rf13734** [comment]
![image](https://user-images.githubusercontent.com/43117750/124740471-1e46ce80-df1b-11eb-997e-bd971db1985b.png)
 Should I be on 'fixes' branch or main?

**Comment by luiztauffer** [comment]
@rf13734 you should be on fixes branch of this repo here.
for NEO I believe you should be on main branch

**Comment by rf13734** [comment]
Cool! I did this @luiztauffer, and it fixed the issue I was having up top.

![image](https://user-images.githubusercontent.com/43117750/124746120-ce6b0600-df20-11eb-8984-309f5a366f59.png)
 
However, I'm still getting this error about the starting time being int64 rather than float. 
![image](https://user-images.githubusercontent.com/43117750/124745977-ae3b4700-df20-11eb-850b-804b685bc6a0.png)

Might this be because I'm loading in a bin file rather than smrx?

**Comment by luiztauffer** [comment]
@rf13734 please update nwb-conversion-tools and let us know if this was fixed:
```
pip install -U nwb-conversion-tools
```

**Comment by rf13734** [comment]
@luiztauffer  Is this right?

![image](https://user-images.githubusercontent.com/43117750/124755192-5950fe00-df2b-11eb-8955-b4f197cc63f1.png)

![image](https://user-images.githubusercontent.com/43117750/124755315-7e457100-df2b-11eb-8410-5ea58efda4e0.png)

It now asks me to install this opencv-pyhton, which I did 
![image](https://user-images.githubusercontent.com/43117750/124755455-adf47900-df2b-11eb-9cc4-c60371da81cf.png)

![image](https://user-images.githubusercontent.com/43117750/124755564-cf556500-df2b-11eb-9710-cf3564014ddb.png)

but I still get the error.

![image](https://user-images.githubusercontent.com/43117750/124755659-edbb6080-df2b-11eb-9d77-7bfc7afc3c44.png)

**Comment by rf13734** [comment]
This also occurs in the same error message 
![image](https://user-images.githubusercontent.com/43117750/124758146-95399280-df2e-11eb-9cc8-06a8c1fc3875.png)

**Comment by luiztauffer** [comment]
@rf13734 ok, I believe opencv this shouldn't be required for your converter, I'll check with the dev team so we can remove this requirement, thanks for finding that out!

**Comment by rf13734** [comment]
@luiztauffer Okay thanks!

**Comment by CodyCBakerPhD** [comment]
@rf13734 @luiztauffer Sorry you ran into this problem - please try installing nwb-conversion-tools from master branch similar to how you did neo earlier.

`pip install git+https://github.com/CatalystNeuro/nwb-conversion-tools.git`

**Comment by rf13734** [comment]
Thanks for taking a look at it @CodyCBakerPhD @luiztauffer . It fixed the OpenCV issue. I'm still struggling to save the LFPs though, with the same error.

![image](https://user-images.githubusercontent.com/43117750/124800166-a053e900-df55-11eb-8475-d48ceef8d51f.png)


![image](https://user-images.githubusercontent.com/43117750/124799989-6c78c380-df55-11eb-9441-3c12fbe1251f.png)
![image](https://user-images.githubusercontent.com/43117750/124800023-77335880-df55-11eb-9a3c-f7cd009433e0.png)
![image](https://user-images.githubusercontent.com/43117750/124800064-82868400-df55-11eb-9d63-508c94d6126c.png)
![image](https://user-images.githubusercontent.com/43117750/124800106-8dd9af80-df55-11eb-8b64-4c1d53cffcb4.png)

**Comment by CodyCBakerPhD** [comment]
@rf13734 So sorry about these issues; the API has changed a lot in the past 6 months. It looks like we had originally developed and debugged these tools under nwb-conversion-tools v0.6.3. If you're willing, try

`pip install nwb-conversion-tools==0.6.3`

and see if that resolves the non-import issues you're observing. It should in theory work unless the repo uses newer features (@luiztauffer are they using any newer features developed since then?)

**Comment by rf13734** [comment]
@CodyCBakerPhD  @luiztauffer 


![image](https://user-images.githubusercontent.com/43117750/124806257-c8931600-df5c-11eb-893c-cfe3def54c33.png)

When I install 0.6.3 I get an different error with the imports
![image](https://user-images.githubusercontent.com/43117750/124806226-bd3fea80-df5c-11eb-889a-1896f887281c.png)

**Comment by CodyCBakerPhD** [comment]
Ah, so the current CEDNWBConverter indeed uses the newer version of the API. Ignore the bit about v0.6.3, then.

@alejoe91 In your opinion, should we fix this on spikeextractors so that sampling frequencies always return floats, or on nwb-conversion-tools and just hard cast them before electrical series write?

**Comment by alejoe91** [comment]
@CodyCBakerPhD doesn't hurt to hard cast in the conversion tools ;)

**Comment by CodyCBakerPhD** [comment]
I've made a PR for this fix [here](https://github.com/catalystneuro/nwb-conversion-tools/pull/208).

Feel free to directly install the branch until it gets merged to try to proceed along the pipeline

`pip install git+https://github.com/CatalystNeuro/nwb-conversion-tools.git@fix_issue_207`

**Comment by CodyCBakerPhD** [comment]
The `starting_time` issue has now been fixed and merged to master; please try again

`pip install git+https://github.com/CatalystNeuro/nwb-conversion-tools.git`

**Comment by rf13734** [comment]
@CodyCBakerPhD 

Thanks very much! Looks to have worked. 

![image](https://user-images.githubusercontent.com/43117750/124880581-bd78ce00-dfce-11eb-959a-674a9b7ffba1.png)


![image](https://user-images.githubusercontent.com/43117750/124880531-adf98500-dfce-11eb-8bea-dfeec3ad8aa7.png)
