### ISSUE TITLE
Different number of rising/falling edges

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#47]
Hi there, I'm trying to add some TTL traces from CED into and existing nwb file with a notebook from I think @CodyCBakerPhD . I run into the following issue.

![image](https://user-images.githubusercontent.com/43117750/137122831-1cc46119-1e73-4b1f-8cc1-88af017a402e.png)
![image](https://user-images.githubusercontent.com/43117750/137122859-2f34da19-1d87-4b87-8dc2-c22833a2bf99.png)

When ignoring this line, the code runs, but I'm wondering how vital this line is, and whether the resulting file will make sense without it.

Any help would be much appreciated!

All the best

Ross

**Comment by lkeegan** [comment]
@alejoe91 this is the current workaround: https://github.com/ssciwr/mease-lab-to-nwb/commit/a176822dcf034273c0426a009f7b493297e01c9b

Also here are the identified rising/falling edges for the file where this issue occurs: both the first and last edge are identified as falling edges, which causes the error message:

first few points:
![rising-falling-start](https://user-images.githubusercontent.com/12845624/137126797-7c154e6f-5909-46de-b7ac-bc6c9a1330e4.png)

last few points:
![rising-falling-end](https://user-images.githubusercontent.com/12845624/137126806-beb62718-8718-4ef0-a07b-a3d293a2cbbd.png)

**Comment by alejoe91** [comment]
> > Thanks @lkeegan. The fix is exactly what I would have done. Note that the function is designed for TTL signals, while the plots you shared don't look like TTL signals at all. Is that supposed to look like that?
> 
> @alessio as far as I'm aware it comes from the first 400 samples of the laser TTL trace (smrx_channel_ids = 73), have I got that right @lkeegan?
> 
> ![image](https://user-images.githubusercontent.com/43117750/137180827-f064fd93-5743-4055-8d33-41e93feb752b.png)

Ok then what I would do is binarize the signal. You can set all the `values < max(trace) / 2` to 0 and `values > max(traces) / 2` to 1. Then the diff should be much more robust. Can you try that?

**Comment by lkeegan** [comment]
@alejoe91 thanks for your help with this - it turned out this channel was just noise (there was no TTL data in this particular recording & channel). #48 adds a check that the channel contains valid-looking TTL data before processing it.
